Distinguish failure modes
Not having changes to release or already being on the latest release are
"non-failure" exit modes, but must terminate as an error.

Being on the wrong branch or having unexpected changes (in strict mode)
are failure modes that are more "serious".

The intention is that the former (exit 1) will stop the GitHub workflow,
but report the job as a success. The latter (exit 2) will stop the
workflow and report the job as a failure.

diff --git a/script/preversion b/script/preversion
--- a/script/preversion
+++ b/script/preversion
@@ -35,8 +35,8 @@ if [ "${1-}" = -- ]; then
 fi
 
 abort() {
-  echo "Aborting: $*" >&2
-  exit 1
+  echo "Aborting: $1" >&2
+  exit "${2:-1}"
 }
 
 declare -a files
@@ -57,7 +57,7 @@ fi
 
 current_branch="$(git symbolic-ref --short HEAD)"
 if [ "$current_branch" != master ]; then
-  abort "Not currently on master branch"
+  abort "Not currently on master branch" 2
 fi
 
 previous_tag="$(git describe --tags --abbrev=0)"
@@ -67,7 +67,7 @@ fi
 
 if [ -n "${strict-}" ] &&
   ! git diff --quiet "${previous_tag}..HEAD" -- ":!${files[*]}"; then
-  abort "Changes detected outside '${files[*]}'"
+  abort "Changes detected outside '${files[*]}'" 2
 fi
 
 if [ -n "${verbose-}" ]; then
